name: bus_number
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
  - python>=3.6

